In [58]:
import tensorflow as tf
import keras as k
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
#jupyter Notebook 내부에 그래프를 출력하도록 설정
%matplotlib inline
import seaborn as sns

In [79]:
swing_dir= "./swing/"
data = pd.read_csv(swing_dir+"golf1.csv")

In [80]:
for i in range(1,5):
    temp = pd.read_csv(swing_dir+"golf"+str(i+1)+".csv")
    data = data.append(temp,ignore_index=True)

In [81]:
len(data)
#현재 data수는 총 5개.

626

In [82]:
data

         time     X_value       Y_value   Z_value
0    Started:  8월 19 2019  15:06:36:902
1      0.0000     0.00000       0.00000   0.00000
2      0.0030    -0.17909      -0.15016  -0.11115
3      0.0446     0.17801      -0.11336   0.67382
4      0.0854    -0.31890      -0.06111   0.24877
..        ...         ...           ...       ...
621    4.4661    -2.76631      -1.35828   1.82010
622    4.5030    -2.47535      -1.29011   1.42082
623    4.5448    -2.08231      -1.22664   1.56850
624    4.5826    -1.77547      -1.14557   1.10392
625    4.6223    -1.41437      -1.06624   1.04742

[626 rows x 4 columns]

In [105]:
cnt = 1
start,end = 1,0
for i in range(1,len(data)):
    if data['time'][i]=="Started:":
        print(data.loc[i])
        print("--------",cnt,"---------------")
        cnt+=1
        print("---------",i,"----------------")
        end = i-1
        print(start,end,end-start)
        start=end+1
        continue
    data.loc[i] = data.loc[i].astype(float)
#한 데이터당 길이는 대략 130
#길이를 130으로 고정.

time           Started:
X_value      8월 19 2019
Y_value    15:07:12:146
Z_value
Name: 135, dtype: object
-------- 1 ---------------
--------- 135 ----------------
1 134 133
time           Started:
X_value      8월 19 2019
Y_value    15:07:50:716
Z_value
Name: 264, dtype: object
-------- 2 ---------------
--------- 264 ----------------
135 263 128
time           Started:
X_value      8월 19 2019
Y_value    15:08:22:456
Z_value
Name: 389, dtype: object
-------- 3 ---------------
--------- 389 ----------------
264 388 124
time           Started:
X_value      8월 19 2019
Y_value    15:08:56:766
Z_value
Name: 508, dtype: object
-------- 4 ---------------
--------- 508 ----------------
389 507 118

In [107]:
X = np.zeros((3,130))
np.concatenate()

In [63]:
np

626

In [64]:
data.head()

       time     X_value       Y_value   Z_value
0  Started:  8월 19 2019  15:06:36:902
1    0.0000     0.00000       0.00000   0.00000
2    0.0030    -0.17909      -0.15016  -0.11115
3    0.0446     0.17801      -0.11336   0.67382
4    0.0854    -0.31890      -0.06111   0.24877

In [65]:
for col in data.columns:
    data[col].astype(float)

ValueError: could not convert string to float: 'Started:'

In [57]:
data['time']

1      0.0000
2      0.0030
3      0.0446
4      0.0854
5      0.1246
        ...
113    4.4661
114    4.5030
115    4.5448
116    4.5826
117    4.6223
Name: time, Length: 621, dtype: object